# Generated by Django 4.2.4 on 2023-10-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=50)),
                ('activity_desc', models.TextField()),
                ('activity_time', models.DateTimeField()),
            ],
        ),
    ]
