# Generated by Django 4.2.4 on 2023-10-29 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='activity_time',
        ),
        migrations.AddField(
            model_name='todo',
            name='activity_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 17, 54, 1, 981719)),
        ),
    ]
