# Generated by Django 4.2.4 on 2023-10-31 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_todo_activity_time_todo_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='activity_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 12, 42, 36, 441769)),
        ),
    ]
