# Generated by Django 4.2.4 on 2023-10-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_todo_activity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='activity_date',
        ),
    ]
