# Generated by Django 4.2.4 on 2023-10-31 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_todo_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 21, 20, 17, 117255)),
        ),
    ]
